### ISSUE TITLE
Grid offset 

### ISSUE THREAD

**Issue by Timopheym** [heavysixer/d4#10]
If i create a grid for bar chat, the grid line goes throw the group. But i want to set it between the lines. How could it be done in a more elegant way?  
![screen shot 2014-05-12 at 8 20 56 pm](https://cloud.githubusercontent.com/assets/525039/2947017/a7b7b1de-d9f1-11e3-91dd-834310b56053.png)

**Comment by heavysixer** [comment]
Fixed in release ed84d7eaab1d1fce5b738ad5acb73301b7d24c3c
