### ISSUE TITLE
Tick offset

### ISSUE THREAD

**Issue by Timopheym** [heavysixer/d4#25]
Is it normal, that tick is not centred in the middle of the columns?
You can have a look here: http://jsbin.com/ciyihi/2/edit

![screen_shot_2014-10-21_at_6 00 18_pm](https://cloud.githubusercontent.com/assets/525039/4988497/fa62cf1c-6976-11e4-93ff-436dda205a1d.png)

Where can it be changed?

**Comment by heavysixer** [comment]
Fixed in release ed84d7eaab1d1fce5b738ad5acb73301b7d24c3c
