### ISSUE TITLE
Scales shouldn't auto-nice without an option to prevent it

### ISSUE THREAD

**Issue by yanofsky** [heavysixer/d4#32]
Every scale created by D4 has `nice()` called on it https://github.com/heavysixer/d4/blob/8136c16dff754ea227c86218f69a8f5179a96faa/src/builders/scales.js#L63

Since there is no way to un-nice a d3 scale (that I know of) there should be a way to turn this off (or prevent it from happening entirely)

**Comment by heavysixer** [comment]
this seems very reasonable, let me investigate on how to best implement this.
