### ISSUE TITLE
Throws reference error when using Browserify (assuming will also throw error with other bundlers?) 

### ISSUE THREAD

**Issue by LomaxRx** [heavysixer/d4#44]
Looks like d4 variable isn't available inside subsequent closures after the first when compiling with Browserify. As a quick-fix, I declared d4 variable outside all closures. Thoughts?

```javascript
var d4;

(function() {
  'use strict';

  var root = this;
  var breaker = {};

  // Create a safe reference to the d4 object.
  d4 = function(obj) {
    if (obj instanceof d4) {
      return obj;
    }
    if (!(this instanceof d4)) {
      return new d4(obj);
    }
    this.d4Wrapped = obj;
  };
...
```

**Comment by heavysixer** [comment]
Looks reasonable to me. I'd suggest making this change as a PR after you ensure all tests pass (and adding tests as you feel necessary). I'd be happy to merge it down then.

**Comment by heavysixer** [comment]
closing this due to the PR you submitted.
